#if !canImport(ObjectiveC)
import XCTest

extension SymbolGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SymbolGraphTests = [
        ("testDeserialization", testDeserialization),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SymbolGraphTests.__allTests__SymbolGraphTests),
    ]
}
#endif
